apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cm-nginx-ingress
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http-metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: app
  namespaceSelector:
    matchNames:
    - nginx-ingress
  selector:
    matchLabels:
      app: cm-nginx-ingress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cm-nginx-ingress
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  ports:
  - name: http-metrics
    port: 10254
    protocol: TCP
    targetPort: 10254
  selector:
    app: nginx-ingress
    component: controller
  sessionAffinity: None
  type: ClusterIP

# tke
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cm-tke-nginx-ingress
  name: tke-nginx-ingress
  namespace: kube-system
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http-metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: cm-tke-nginx-ingress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cm-tke-nginx-ingress
  name: tke-nginx-ingress
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 10254
    protocol: TCP
    targetPort: 10254
  selector:
    k8s-app: nginx-qa-ingress-nginx-controller
  sessionAffinity: None
  type: ClusterIP